import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/cartContext";
import SettingsButton from "./components/SettingsButton";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ohio State Pizzas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Directly use the image URL for all favicon needs */}
        <link 
          rel="icon" 
          href="../../assets/title_logo.png"
          type="image/png" 
        />
        
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <div className="fixed top-4 right-4 z-50">
            <SettingsButton />
          </div>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
